"""followers

Revision ID: 33384d4d6591
Revises: 0cc40267d2a1
Create Date: 2019-03-25 08:09:13.451862

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33384d4d6591'
down_revision = '0cc40267d2a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
